### ISSUE TITLE
Support needed for latest NHibernate version 3.3.3.4001  (3.3.3SP1)

### ISSUE THREAD

**Issue by EricPower** [ranzlee/NHibernate.Extensions#4]
I must upgrade to NHibernate version 3.3.3.4001 released on 8/8/2013 to get a bug fix I've been waiting forever on.  (http://sourceforge.net/projects/nhibernate/files/NHibernate/3.3.3SP1/)

But I cannot upgrade one of my projects because NHibernate.Glimpse doesn't support that NHibernate Dependency version.

Can you update the required NHibernate Dependency to allow 3.3.3.4001 ?

**Comment by ranzlee** [comment]
Hi Eric,

I will be updating the NH extensions (including Glimpse) this week sometime.  If you need it before then, just pull the source from Git and update the NH reference.  Nothing in the NH logging framework should have changed, and that would be the only thing that could break the Glimpse plugin.

Thanks,

Randy

From: EricPower
Sent: ‎Friday‎, ‎August‎ ‎09‎, ‎2013 ‎12‎:‎39‎ ‎PM
To: ranzlee/NHibernate.Extensions

I must upgrade to NHibernate version 3.3.3.4001 released on 8/8/2013 to get a bug fix I've been waiting forever on. (http://sourceforge.net/projects/nhibernate/files/NHibernate/3.3.3SP1/)

But I cannot upgrade one of my projects because NHibernate.Glimpse doesn't support that NHibernate Dependency version.

Can you update the required NHibernate Dependency to allow 3.3.3.4001 ?

**Comment by crmckenzie** [comment]
+1, I'm happy to submit a pull request. It seems like the problem could be fixed just by updating your nuspec to >= 3.3.3.4000 instead of taking a hard dependency on a specific package version.

Let me know if you want me to do the pull request.

**Comment by EricPower** [comment]
Yes,  please do. Thanks. Updated my nuspec file locally worked for me. 

Sent from my Verizon Wireless 4G LTE Smartphone

-------- Original message --------

**Comment by BredStik** [comment]
"It seems like the problem could be fixed just by updating your nuspec to >= 3.3.3.4000 instead of taking a hard dependency on a specific package version."

+1
